'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class TrackConfirm
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblTitle As System.Web.UI.WebControls.Label
    Protected WithEvents trHeader As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblPR As System.Web.UI.WebControls.Label
    Protected WithEvents trItem As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblItem As System.Web.UI.WebControls.Label
    Protected WithEvents trSpace As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents trHeaderFail As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblPRFail As System.Web.UI.WebControls.Label
    Protected WithEvents trItemFail As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblItemFail As System.Web.UI.WebControls.Label
    Protected WithEvents lnkBack As System.Web.UI.WebControls.HyperLink
End Class
