'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class AddressMaster
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblTitle As System.Web.UI.WebControls.Label
    Protected WithEvents txt_Code As System.Web.UI.WebControls.TextBox
    Protected WithEvents txt_Address As System.Web.UI.WebControls.TextBox
    Protected WithEvents txt_City As System.Web.UI.WebControls.TextBox
    Protected WithEvents cbo_State As System.Web.UI.WebControls.DropDownList
    Protected WithEvents cmd_Search As System.Web.UI.WebControls.Button
    Protected WithEvents dtgAddress As System.Web.UI.WebControls.DataGrid
    Protected WithEvents trT As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents cmd_Add As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_Modify As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_Delete As System.Web.UI.WebControls.Button
    Protected WithEvents cmdReset As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents trP As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents cmdSelect As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents hidID As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidMode As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidItem As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidIndex As System.Web.UI.HtmlControls.HtmlInputHidden
End Class
