'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BComParam
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblHeader As System.Web.UI.WebControls.Label
    Protected WithEvents txt_RfqPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revRFQPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_RfqLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revRFQLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PrPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPRPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PrLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPRLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PoPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPOPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PoLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPOLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_GrnPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revGRNPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_GrnLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revGRNLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_SrnPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revSRNPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_SrnLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revSRNLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PayPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPayPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_PayLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revPayLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_TenPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revTenPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_TenLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revTenLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_DebitPre As System.Web.UI.WebControls.TextBox
    Protected WithEvents revDebitPre As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txt_DebitLun As System.Web.UI.WebControls.TextBox
    Protected WithEvents revDebitLun As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents opl_RfqOp As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents ChkFreeForm As System.Web.UI.WebControls.CheckBox
    Protected WithEvents ChkConsolidation As System.Web.UI.WebControls.CheckBox
    Protected WithEvents ChkLevelsRec As System.Web.UI.WebControls.CheckBox
    Protected WithEvents Label4 As System.Web.UI.WebControls.Label
    Protected WithEvents cmd_save As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_Reset As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents hidMode As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents vldSumm As System.Web.UI.WebControls.ValidationSummary
End Class
