'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ProductDetail
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lbl_txproid As System.Web.UI.WebControls.Label
    Protected WithEvents tdImage As System.Web.UI.HtmlControls.HtmlTableCell
    Protected WithEvents lblProdImage As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_venitemcode As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_prodesc As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_unspsc As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_ven As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_brand As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_model As System.Web.UI.WebControls.Label
    Protected WithEvents MyDataGrid As System.Web.UI.WebControls.DataGrid
    Protected WithEvents tdAttach As System.Web.UI.HtmlControls.HtmlTableCell
End Class
