'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Favs_BuyerList
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents rdSearch As System.Web.UI.WebControls.RadioButtonList
    Protected WithEvents cboCatalogueBuyer As System.Web.UI.WebControls.DropDownList
    Protected WithEvents cboCatalogueFav As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtVendorItem As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtBuyerItem As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtVendorName As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDesc As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmdSearch As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_Clear As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents Div_Buyer As System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents dtgBuyer As System.Web.UI.WebControls.DataGrid
    Protected WithEvents Div_Fav As System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents dtgFavs As System.Web.UI.WebControls.DataGrid
    Protected WithEvents cmd_Add As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_Remove As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_RemoveAll As System.Web.UI.WebControls.Button
    Protected WithEvents hidIndex As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidDelete As System.Web.UI.HtmlControls.HtmlInputHidden
End Class
