'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class PersonalDetails
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblUserID As System.Web.UI.WebControls.Label
    Protected WithEvents txtUserName As System.Web.UI.WebControls.TextBox
    Protected WithEvents vldName As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents lblUserRole As System.Web.UI.WebControls.Label
    Protected WithEvents lblDeptName As System.Web.UI.WebControls.Label
    Protected WithEvents txtEmail As System.Web.UI.WebControls.TextBox
    Protected WithEvents vldEmail As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents revEmail As System.Web.UI.WebControls.RegularExpressionValidator
    Protected WithEvents txtPhone As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtFax As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtDesination As System.Web.UI.WebControls.TextBox
    Protected WithEvents vldDesignation As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtNewPW As System.Web.UI.WebControls.TextBox
    Protected WithEvents txtConfNPW As System.Web.UI.WebControls.TextBox
    Protected WithEvents lblExpPW As System.Web.UI.WebControls.Label
    Protected WithEvents cboPageCnt As System.Web.UI.WebControls.DropDownList
    Protected WithEvents trCCList As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents txtCCList As System.Web.UI.WebControls.TextBox
    Protected WithEvents cvEmail As System.Web.UI.WebControls.CustomValidator
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents cmdSave As System.Web.UI.WebControls.Button
    Protected WithEvents cmdReset As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents hidDeptID As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidStatus As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidDelInd As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidAppLimit As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidNewPW As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidConPW As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents hidInvAppLimit As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents vldSumm As System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents lblMsg2 As System.Web.UI.WebControls.Label
End Class
