'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("PaymentAdvice"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class PaymentAdvice
    Inherits Global.System.Data.DataSet
    
    Private tablePaymentAdvice As PaymentAdviceDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("PaymentAdvice")) Is Nothing) Then
                MyBase.Tables.Add(New PaymentAdviceDataTable(ds.Tables("PaymentAdvice")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property _PaymentAdvice() As PaymentAdviceDataTable
        Get
            Return Me.tablePaymentAdvice
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As PaymentAdvice = CType(MyBase.Clone,PaymentAdvice)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("PaymentAdvice")) Is Nothing) Then
                MyBase.Tables.Add(New PaymentAdviceDataTable(ds.Tables("PaymentAdvice")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablePaymentAdvice = CType(MyBase.Tables("PaymentAdvice"),PaymentAdviceDataTable)
        If (initTable = true) Then
            If (Not (Me.tablePaymentAdvice) Is Nothing) Then
                Me.tablePaymentAdvice.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "PaymentAdvice"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/PaymentAdvice.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablePaymentAdvice = New PaymentAdviceDataTable
        MyBase.Tables.Add(Me.tablePaymentAdvice)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerialize_PaymentAdvice() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As PaymentAdvice = New PaymentAdvice
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub PaymentAdviceRowChangeEventHandler(ByVal sender As Object, ByVal e As PaymentAdviceRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class PaymentAdviceDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnPayAdviseNo As Global.System.Data.DataColumn
        
        Private columnic_addr_line1 As Global.System.Data.DataColumn
        
        Private columnic_addr_line2 As Global.System.Data.DataColumn
        
        Private columnic_addr_line3 As Global.System.Data.DataColumn
        
        Private columnic_postcode As Global.System.Data.DataColumn
        
        Private columnic_city As Global.System.Data.DataColumn
        
        Private columnic_bank_code As Global.System.Data.DataColumn
        
        Private columnic_bank_acct As Global.System.Data.DataColumn
        
        Private columnic_state As Global.System.Data.DataColumn
        
        Private columnic_country As Global.System.Data.DataColumn
        
        Private columnic_phone As Global.System.Data.DataColumn
        
        Private columnic_fax As Global.System.Data.DataColumn
        
        Private columnBankCharge As Global.System.Data.DataColumn
        
        Private columnim_currency_code As Global.System.Data.DataColumn
        
        Private columnim_invoice_total2 As Global.System.Data.DataColumn
        
        Private columnim_payment_term As Global.System.Data.DataColumn
        
        Private columnim_invoice_no As Global.System.Data.DataColumn
        
        Private columnim_invoice_type As Global.System.Data.DataColumn
        
        Private columnim_doc_date As Global.System.Data.DataColumn
        
        Private columnim_invoice_total As Global.System.Data.DataColumn
        
        Private columnim_s_coy_id As Global.System.Data.DataColumn
        
        Private columnim_s_coy_name As Global.System.Data.DataColumn
        
        Private columnim_withholding_tax As Global.System.Data.DataColumn
        
        Private columnim_withholding_opt As Global.System.Data.DataColumn
        
        Private columnim_cheque_no As Global.System.Data.DataColumn
        
        Private columnim_payment_date As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "PaymentAdvice"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PayAdviseNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPayAdviseNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_addr_line1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_addr_line1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_addr_line2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_addr_line2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_addr_line3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_addr_line3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_postcodeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_postcode
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_cityColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_city
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_bank_codeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_bank_code
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_bank_acctColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_bank_acct
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_stateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_state
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_countryColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_country
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_phoneColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_phone
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ic_faxColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnic_fax
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BankChargeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBankCharge
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_currency_codeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_currency_code
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_invoice_total2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_invoice_total2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_payment_termColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_payment_term
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_invoice_noColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_invoice_no
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_invoice_typeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_invoice_type
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_doc_dateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_doc_date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_invoice_totalColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_invoice_total
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_s_coy_idColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_s_coy_id
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_s_coy_nameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_s_coy_name
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_withholding_taxColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_withholding_tax
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_withholding_optColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_withholding_opt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_cheque_noColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_cheque_no
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property im_payment_dateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnim_payment_date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As PaymentAdviceRow
            Get
                Return CType(Me.Rows(index),PaymentAdviceRow)
            End Get
        End Property
        
        Public Event PaymentAdviceRowChanging As PaymentAdviceRowChangeEventHandler
        
        Public Event PaymentAdviceRowChanged As PaymentAdviceRowChangeEventHandler
        
        Public Event PaymentAdviceRowDeleting As PaymentAdviceRowChangeEventHandler
        
        Public Event PaymentAdviceRowDeleted As PaymentAdviceRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddPaymentAdviceRow(ByVal row As PaymentAdviceRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddPaymentAdviceRow( _
                    ByVal PayAdviseNo As String,  _
                    ByVal ic_addr_line1 As String,  _
                    ByVal ic_addr_line2 As String,  _
                    ByVal ic_addr_line3 As String,  _
                    ByVal ic_postcode As String,  _
                    ByVal ic_city As String,  _
                    ByVal ic_bank_code As String,  _
                    ByVal ic_bank_acct As String,  _
                    ByVal ic_state As String,  _
                    ByVal ic_country As String,  _
                    ByVal ic_phone As String,  _
                    ByVal ic_fax As String,  _
                    ByVal BankCharge As String,  _
                    ByVal im_currency_code As String,  _
                    ByVal im_invoice_total2 As Decimal,  _
                    ByVal im_payment_term As String,  _
                    ByVal im_invoice_no As String,  _
                    ByVal im_invoice_type As String,  _
                    ByVal im_doc_date As Date,  _
                    ByVal im_invoice_total As Decimal,  _
                    ByVal im_s_coy_id As String,  _
                    ByVal im_s_coy_name As String,  _
                    ByVal im_withholding_tax As Integer,  _
                    ByVal im_withholding_opt As String,  _
                    ByVal im_cheque_no As String,  _
                    ByVal im_payment_date As Date) As PaymentAdviceRow
            Dim rowPaymentAdviceRow As PaymentAdviceRow = CType(Me.NewRow,PaymentAdviceRow)
            Dim columnValuesArray() As Object = New Object() {PayAdviseNo, ic_addr_line1, ic_addr_line2, ic_addr_line3, ic_postcode, ic_city, ic_bank_code, ic_bank_acct, ic_state, ic_country, ic_phone, ic_fax, BankCharge, im_currency_code, im_invoice_total2, im_payment_term, im_invoice_no, im_invoice_type, im_doc_date, im_invoice_total, im_s_coy_id, im_s_coy_name, im_withholding_tax, im_withholding_opt, im_cheque_no, im_payment_date}
            rowPaymentAdviceRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowPaymentAdviceRow)
            Return rowPaymentAdviceRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As PaymentAdviceDataTable = CType(MyBase.Clone,PaymentAdviceDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New PaymentAdviceDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnPayAdviseNo = MyBase.Columns("PayAdviseNo")
            Me.columnic_addr_line1 = MyBase.Columns("ic_addr_line1")
            Me.columnic_addr_line2 = MyBase.Columns("ic_addr_line2")
            Me.columnic_addr_line3 = MyBase.Columns("ic_addr_line3")
            Me.columnic_postcode = MyBase.Columns("ic_postcode")
            Me.columnic_city = MyBase.Columns("ic_city")
            Me.columnic_bank_code = MyBase.Columns("ic_bank_code")
            Me.columnic_bank_acct = MyBase.Columns("ic_bank_acct")
            Me.columnic_state = MyBase.Columns("ic_state")
            Me.columnic_country = MyBase.Columns("ic_country")
            Me.columnic_phone = MyBase.Columns("ic_phone")
            Me.columnic_fax = MyBase.Columns("ic_fax")
            Me.columnBankCharge = MyBase.Columns("BankCharge")
            Me.columnim_currency_code = MyBase.Columns("im_currency_code")
            Me.columnim_invoice_total2 = MyBase.Columns("im_invoice_total2")
            Me.columnim_payment_term = MyBase.Columns("im_payment_term")
            Me.columnim_invoice_no = MyBase.Columns("im_invoice_no")
            Me.columnim_invoice_type = MyBase.Columns("im_invoice_type")
            Me.columnim_doc_date = MyBase.Columns("im_doc_date")
            Me.columnim_invoice_total = MyBase.Columns("im_invoice_total")
            Me.columnim_s_coy_id = MyBase.Columns("im_s_coy_id")
            Me.columnim_s_coy_name = MyBase.Columns("im_s_coy_name")
            Me.columnim_withholding_tax = MyBase.Columns("im_withholding_tax")
            Me.columnim_withholding_opt = MyBase.Columns("im_withholding_opt")
            Me.columnim_cheque_no = MyBase.Columns("im_cheque_no")
            Me.columnim_payment_date = MyBase.Columns("im_payment_date")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnPayAdviseNo = New Global.System.Data.DataColumn("PayAdviseNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPayAdviseNo)
            Me.columnic_addr_line1 = New Global.System.Data.DataColumn("ic_addr_line1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_addr_line1)
            Me.columnic_addr_line2 = New Global.System.Data.DataColumn("ic_addr_line2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_addr_line2)
            Me.columnic_addr_line3 = New Global.System.Data.DataColumn("ic_addr_line3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_addr_line3)
            Me.columnic_postcode = New Global.System.Data.DataColumn("ic_postcode", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_postcode)
            Me.columnic_city = New Global.System.Data.DataColumn("ic_city", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_city)
            Me.columnic_bank_code = New Global.System.Data.DataColumn("ic_bank_code", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_bank_code)
            Me.columnic_bank_acct = New Global.System.Data.DataColumn("ic_bank_acct", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_bank_acct)
            Me.columnic_state = New Global.System.Data.DataColumn("ic_state", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_state)
            Me.columnic_country = New Global.System.Data.DataColumn("ic_country", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_country)
            Me.columnic_phone = New Global.System.Data.DataColumn("ic_phone", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_phone)
            Me.columnic_fax = New Global.System.Data.DataColumn("ic_fax", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnic_fax)
            Me.columnBankCharge = New Global.System.Data.DataColumn("BankCharge", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBankCharge)
            Me.columnim_currency_code = New Global.System.Data.DataColumn("im_currency_code", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_currency_code)
            Me.columnim_invoice_total2 = New Global.System.Data.DataColumn("im_invoice_total2", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_invoice_total2)
            Me.columnim_payment_term = New Global.System.Data.DataColumn("im_payment_term", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_payment_term)
            Me.columnim_invoice_no = New Global.System.Data.DataColumn("im_invoice_no", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_invoice_no)
            Me.columnim_invoice_type = New Global.System.Data.DataColumn("im_invoice_type", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_invoice_type)
            Me.columnim_doc_date = New Global.System.Data.DataColumn("im_doc_date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_doc_date)
            Me.columnim_invoice_total = New Global.System.Data.DataColumn("im_invoice_total", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_invoice_total)
            Me.columnim_s_coy_id = New Global.System.Data.DataColumn("im_s_coy_id", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_s_coy_id)
            Me.columnim_s_coy_name = New Global.System.Data.DataColumn("im_s_coy_name", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_s_coy_name)
            Me.columnim_withholding_tax = New Global.System.Data.DataColumn("im_withholding_tax", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_withholding_tax)
            Me.columnim_withholding_opt = New Global.System.Data.DataColumn("im_withholding_opt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_withholding_opt)
            Me.columnim_cheque_no = New Global.System.Data.DataColumn("im_cheque_no", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_cheque_no)
            Me.columnim_payment_date = New Global.System.Data.DataColumn("im_payment_date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnim_payment_date)
            Me.columnPayAdviseNo.AllowDBNull = false
            Me.columnic_addr_line1.MaxLength = 255
            Me.columnic_addr_line2.MaxLength = 255
            Me.columnic_addr_line3.MaxLength = 255
            Me.columnic_postcode.MaxLength = 5
            Me.columnic_city.MaxLength = 50
            Me.columnic_bank_code.MaxLength = 30
            Me.columnic_bank_acct.MaxLength = 30
            Me.columnic_state.MaxLength = 50
            Me.columnic_country.MaxLength = 50
            Me.columnic_phone.MaxLength = 20
            Me.columnic_fax.MaxLength = 20
            Me.columnBankCharge.AllowDBNull = false
            Me.columnim_currency_code.MaxLength = 10
            Me.columnim_payment_term.MaxLength = 10
            Me.columnim_invoice_no.MaxLength = 50
            Me.columnim_invoice_type.MaxLength = 6
            Me.columnim_s_coy_id.MaxLength = 20
            Me.columnim_s_coy_name.MaxLength = 100
            Me.columnim_withholding_opt.MaxLength = 1
            Me.columnim_cheque_no.MaxLength = 20
            Me.ExtendedProperties.Add("Generator_TablePropName", "_PaymentAdvice")
            Me.ExtendedProperties.Add("Generator_UserTableName", "PaymentAdvice")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewPaymentAdviceRow() As PaymentAdviceRow
            Return CType(Me.NewRow,PaymentAdviceRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New PaymentAdviceRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(PaymentAdviceRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PaymentAdviceRowChangedEvent) Is Nothing) Then
                RaiseEvent PaymentAdviceRowChanged(Me, New PaymentAdviceRowChangeEvent(CType(e.Row,PaymentAdviceRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PaymentAdviceRowChangingEvent) Is Nothing) Then
                RaiseEvent PaymentAdviceRowChanging(Me, New PaymentAdviceRowChangeEvent(CType(e.Row,PaymentAdviceRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PaymentAdviceRowDeletedEvent) Is Nothing) Then
                RaiseEvent PaymentAdviceRowDeleted(Me, New PaymentAdviceRowChangeEvent(CType(e.Row,PaymentAdviceRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PaymentAdviceRowDeletingEvent) Is Nothing) Then
                RaiseEvent PaymentAdviceRowDeleting(Me, New PaymentAdviceRowChangeEvent(CType(e.Row,PaymentAdviceRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemovePaymentAdviceRow(ByVal row As PaymentAdviceRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As PaymentAdvice = New PaymentAdvice
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "PaymentAdviceDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class PaymentAdviceRow
        Inherits Global.System.Data.DataRow
        
        Private tablePaymentAdvice As PaymentAdviceDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablePaymentAdvice = CType(Me.Table,PaymentAdviceDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PayAdviseNo() As String
            Get
                Return CType(Me(Me.tablePaymentAdvice.PayAdviseNoColumn),String)
            End Get
            Set
                Me(Me.tablePaymentAdvice.PayAdviseNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_addr_line1() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_addr_line1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_addr_line1' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_addr_line1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_addr_line2() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_addr_line2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_addr_line2' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_addr_line2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_addr_line3() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_addr_line3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_addr_line3' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_addr_line3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_postcode() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_postcodeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_postcode' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_postcodeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_city() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_cityColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_city' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_cityColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_bank_code() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_bank_codeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_bank_code' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_bank_codeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_bank_acct() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_bank_acctColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_bank_acct' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_bank_acctColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_state() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_stateColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_state' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_stateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_country() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_countryColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_country' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_countryColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_phone() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_phoneColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_phone' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_phoneColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ic_fax() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.ic_faxColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ic_fax' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.ic_faxColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BankCharge() As String
            Get
                Return CType(Me(Me.tablePaymentAdvice.BankChargeColumn),String)
            End Get
            Set
                Me(Me.tablePaymentAdvice.BankChargeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_currency_code() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_currency_codeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_currency_code' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_currency_codeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_invoice_total2() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_invoice_total2Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_invoice_total2' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_invoice_total2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_payment_term() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_payment_termColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_payment_term' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_payment_termColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_invoice_no() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_invoice_noColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_invoice_no' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_invoice_noColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_invoice_type() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_invoice_typeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_invoice_type' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_invoice_typeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_doc_date() As Date
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_doc_dateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_doc_date' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_doc_dateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_invoice_total() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_invoice_totalColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_invoice_total' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_invoice_totalColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_s_coy_id() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_s_coy_idColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_s_coy_id' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_s_coy_idColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_s_coy_name() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_s_coy_nameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_s_coy_name' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_s_coy_nameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_withholding_tax() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_withholding_taxColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_withholding_tax' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_withholding_taxColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_withholding_opt() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_withholding_optColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_withholding_opt' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_withholding_optColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_cheque_no() As String
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_cheque_noColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_cheque_no' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_cheque_noColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property im_payment_date() As Date
            Get
                Try 
                    Return CType(Me(Me.tablePaymentAdvice.im_payment_dateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'im_payment_date' in table 'PaymentAdvice' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePaymentAdvice.im_payment_dateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_addr_line1Null() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_addr_line1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_addr_line1Null()
            Me(Me.tablePaymentAdvice.ic_addr_line1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_addr_line2Null() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_addr_line2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_addr_line2Null()
            Me(Me.tablePaymentAdvice.ic_addr_line2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_addr_line3Null() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_addr_line3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_addr_line3Null()
            Me(Me.tablePaymentAdvice.ic_addr_line3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_postcodeNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_postcodeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_postcodeNull()
            Me(Me.tablePaymentAdvice.ic_postcodeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_cityNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_cityColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_cityNull()
            Me(Me.tablePaymentAdvice.ic_cityColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_bank_codeNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_bank_codeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_bank_codeNull()
            Me(Me.tablePaymentAdvice.ic_bank_codeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_bank_acctNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_bank_acctColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_bank_acctNull()
            Me(Me.tablePaymentAdvice.ic_bank_acctColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_stateNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_stateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_stateNull()
            Me(Me.tablePaymentAdvice.ic_stateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_countryNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_countryColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_countryNull()
            Me(Me.tablePaymentAdvice.ic_countryColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_phoneNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_phoneColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_phoneNull()
            Me(Me.tablePaymentAdvice.ic_phoneColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isic_faxNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.ic_faxColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setic_faxNull()
            Me(Me.tablePaymentAdvice.ic_faxColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_currency_codeNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_currency_codeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_currency_codeNull()
            Me(Me.tablePaymentAdvice.im_currency_codeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_invoice_total2Null() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_invoice_total2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_invoice_total2Null()
            Me(Me.tablePaymentAdvice.im_invoice_total2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_payment_termNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_payment_termColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_payment_termNull()
            Me(Me.tablePaymentAdvice.im_payment_termColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_invoice_noNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_invoice_noColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_invoice_noNull()
            Me(Me.tablePaymentAdvice.im_invoice_noColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_invoice_typeNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_invoice_typeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_invoice_typeNull()
            Me(Me.tablePaymentAdvice.im_invoice_typeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_doc_dateNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_doc_dateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_doc_dateNull()
            Me(Me.tablePaymentAdvice.im_doc_dateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_invoice_totalNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_invoice_totalColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_invoice_totalNull()
            Me(Me.tablePaymentAdvice.im_invoice_totalColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_s_coy_idNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_s_coy_idColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_s_coy_idNull()
            Me(Me.tablePaymentAdvice.im_s_coy_idColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_s_coy_nameNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_s_coy_nameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_s_coy_nameNull()
            Me(Me.tablePaymentAdvice.im_s_coy_nameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_withholding_taxNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_withholding_taxColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_withholding_taxNull()
            Me(Me.tablePaymentAdvice.im_withholding_taxColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_withholding_optNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_withholding_optColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_withholding_optNull()
            Me(Me.tablePaymentAdvice.im_withholding_optColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_cheque_noNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_cheque_noColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_cheque_noNull()
            Me(Me.tablePaymentAdvice.im_cheque_noColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isim_payment_dateNull() As Boolean
            Return Me.IsNull(Me.tablePaymentAdvice.im_payment_dateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setim_payment_dateNull()
            Me(Me.tablePaymentAdvice.im_payment_dateColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class PaymentAdviceRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As PaymentAdviceRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As PaymentAdviceRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As PaymentAdviceRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace PaymentAdviceTableAdapters
    
    '''<summary>
    '''Represents the connection and commands used to retrieve and save data.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
     Global.System.ComponentModel.ToolboxItem(true),  _
     Global.System.ComponentModel.DataObjectAttribute(true),  _
     Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class PaymentAdviceTableAdapter
        Inherits Global.System.ComponentModel.Component
        
        Private WithEvents _adapter As Global.MySql.Data.MySqlClient.MySqlDataAdapter
        
        Private _connection As Global.MySql.Data.MySqlClient.MySqlConnection
        
        Private _commandCollection() As Global.MySql.Data.MySqlClient.MySqlCommand
        
        Private _clearBeforeFill As Boolean
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private ReadOnly Property Adapter() As Global.MySql.Data.MySqlClient.MySqlDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Property Connection() As Global.MySql.Data.MySqlClient.MySqlConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),Global.MySql.Data.MySqlClient.MySqlCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected ReadOnly Property CommandCollection() As Global.MySql.Data.MySqlClient.MySqlCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitAdapter()
            Me._adapter = New Global.MySql.Data.MySqlClient.MySqlDataAdapter
            Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "PaymentAdvice"
            tableMapping.ColumnMappings.Add("PayAdviseNo", "PayAdviseNo")
            tableMapping.ColumnMappings.Add("ic_addr_line1", "ic_addr_line1")
            tableMapping.ColumnMappings.Add("ic_addr_line2", "ic_addr_line2")
            tableMapping.ColumnMappings.Add("ic_addr_line3", "ic_addr_line3")
            tableMapping.ColumnMappings.Add("ic_postcode", "ic_postcode")
            tableMapping.ColumnMappings.Add("ic_city", "ic_city")
            tableMapping.ColumnMappings.Add("ic_bank_code", "ic_bank_code")
            tableMapping.ColumnMappings.Add("ic_bank_acct", "ic_bank_acct")
            tableMapping.ColumnMappings.Add("ic_state", "ic_state")
            tableMapping.ColumnMappings.Add("ic_country", "ic_country")
            tableMapping.ColumnMappings.Add("ic_phone", "ic_phone")
            tableMapping.ColumnMappings.Add("ic_fax", "ic_fax")
            tableMapping.ColumnMappings.Add("BankCharge", "BankCharge")
            tableMapping.ColumnMappings.Add("im_currency_code", "im_currency_code")
            tableMapping.ColumnMappings.Add("im_invoice_total2", "im_invoice_total2")
            tableMapping.ColumnMappings.Add("im_payment_term", "im_payment_term")
            tableMapping.ColumnMappings.Add("im_invoice_no", "im_invoice_no")
            tableMapping.ColumnMappings.Add("im_invoice_type", "im_invoice_type")
            tableMapping.ColumnMappings.Add("im_doc_date", "im_doc_date")
            tableMapping.ColumnMappings.Add("im_invoice_total", "im_invoice_total")
            tableMapping.ColumnMappings.Add("im_s_coy_id", "im_s_coy_id")
            tableMapping.ColumnMappings.Add("im_s_coy_name", "im_s_coy_name")
            tableMapping.ColumnMappings.Add("im_withholding_tax", "im_withholding_tax")
            tableMapping.ColumnMappings.Add("im_withholding_opt", "im_withholding_opt")
            tableMapping.ColumnMappings.Add("im_cheque_no", "im_cheque_no")
            tableMapping.ColumnMappings.Add("im_payment_date", "im_payment_date")
            Me._adapter.TableMappings.Add(tableMapping)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitConnection()
            Me._connection = New Global.MySql.Data.MySqlClient.MySqlConnection
            Me._connection.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings("eprocureConnectionString1").ConnectionString
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New Global.MySql.Data.MySqlClient.MySqlCommand(0) {}
            Me._commandCollection(0) = New Global.MySql.Data.MySqlClient.MySqlCommand
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT '' AS PayAdviseNo , im_invoice_no, im_invoice_type, im_doc_date, im_invoic"& _ 
                "e_total,  "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"im_s_coy_id, im_s_coy_name, ic_addr_line1, ic_addr_line2, ic_addr_li"& _ 
                "ne3, ic_postcode, ic_city, ic_bank_code,ic_bank_acct, cm2.code_desc as ic_state,"& _ 
                " cm1.code_desc as ic_country, ic_phone, ic_fax, im_payment_term, im_withholding_"& _ 
                "tax, im_withholding_opt, '' as BankCharge,im_cheque_no,im_currency_code, im_invo"& _ 
                "ice_total AS im_invoice_total2,im_payment_date"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM INVOICE_MSTR "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN c"& _ 
                "ompany_mstr ON im_b_coy_id = cm_coy_id "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN ipp_company ON ic_index = im"& _ 
                "_s_coy_id"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN code_mstr cm1 ON cm_country = cm1.code_abbr "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN c"& _ 
                "ode_mstr cm2 ON cm_state = cm2.code_abbr"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WHERE im_invoice_status = 4 "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"AND im_i"& _ 
                "nvoice_type IS NOT NULL "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"AND im_b_coy_id = 'tanac' "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"AND im_payment_date = CURR"& _ 
                "ENT_DATE "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER BY im_s_coy_name,im_payment_term,im_invoice_no "
            Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As PaymentAdvice.PaymentAdviceDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As PaymentAdvice.PaymentAdviceDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As PaymentAdvice.PaymentAdviceDataTable = New PaymentAdvice.PaymentAdviceDataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
    End Class
End Namespace
