'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("PreviewCN"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class PreviewCN
    Inherits Global.System.Data.DataSet
    
    Private tableDataTable1 As DataTable1DataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DataTable1")) Is Nothing) Then
                MyBase.Tables.Add(New DataTable1DataTable(ds.Tables("DataTable1")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DataTable1() As DataTable1DataTable
        Get
            Return Me.tableDataTable1
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As PreviewCN = CType(MyBase.Clone,PreviewCN)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("DataTable1")) Is Nothing) Then
                MyBase.Tables.Add(New DataTable1DataTable(ds.Tables("DataTable1")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDataTable1 = CType(MyBase.Tables("DataTable1"),DataTable1DataTable)
        If (initTable = true) Then
            If (Not (Me.tableDataTable1) Is Nothing) Then
                Me.tableDataTable1.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "PreviewCN"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/PreviewCN.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDataTable1 = New DataTable1DataTable
        MyBase.Tables.Add(Me.tableDataTable1)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeDataTable1() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As PreviewCN = New PreviewCN
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub DataTable1RowChangeEventHandler(ByVal sender As Object, ByVal e As DataTable1RowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DataTable1DataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnV_COY_NAME As Global.System.Data.DataColumn
        
        Private columnV_ADDR_LINE1 As Global.System.Data.DataColumn
        
        Private columnV_ADDR_LINE2 As Global.System.Data.DataColumn
        
        Private columnV_ADDR_LINE3 As Global.System.Data.DataColumn
        
        Private columnV_POSTCODE As Global.System.Data.DataColumn
        
        Private columnV_CITY As Global.System.Data.DataColumn
        
        Private columnV_STATE As Global.System.Data.DataColumn
        
        Private columnV_COUNTRY As Global.System.Data.DataColumn
        
        Private columnV_BUSINESS_REG_NO As Global.System.Data.DataColumn
        
        Private columnV_EMAIL As Global.System.Data.DataColumn
        
        Private columnV_PHONE As Global.System.Data.DataColumn
        
        Private columnCNM_CN_NO As Global.System.Data.DataColumn
        
        Private columnCNM_CREATED_DATE As Global.System.Data.DataColumn
        
        Private columnCNM_CN_TYPE As Global.System.Data.DataColumn
        
        Private columnB_COY_NAME As Global.System.Data.DataColumn
        
        Private columnB_ADDR_LINE1 As Global.System.Data.DataColumn
        
        Private columnB_ADDR_LINE2 As Global.System.Data.DataColumn
        
        Private columnB_ADDR_LINE3 As Global.System.Data.DataColumn
        
        Private columnB_POSTCODE As Global.System.Data.DataColumn
        
        Private columnB_CITY As Global.System.Data.DataColumn
        
        Private columnB_STATE As Global.System.Data.DataColumn
        
        Private columnB_COUNTRY As Global.System.Data.DataColumn
        
        Private columnIM_SHIP_AMT As Global.System.Data.DataColumn
        
        Private columnIM_WITHHOLDING_TAX As Global.System.Data.DataColumn
        
        Private columnCNM_REMARKS As Global.System.Data.DataColumn
        
        Private columnCNM_EXCHANGE_RATE As Global.System.Data.DataColumn
        
        Private columnCND_CN_LINE As Global.System.Data.DataColumn
        
        Private columnID_PRODUCT_DESC As Global.System.Data.DataColumn
        
        Private columnID_UOM As Global.System.Data.DataColumn
        
        Private columnID_GST As Global.System.Data.DataColumn
        
        Private columnID_GST_RATE As Global.System.Data.DataColumn
        
        Private columnCND_QTY As Global.System.Data.DataColumn
        
        Private columnCND_UNIT_COST As Global.System.Data.DataColumn
        
        Private columnCND_REMARKS As Global.System.Data.DataColumn
        
        Private columnCNM_CURRENCY_CODE As Global.System.Data.DataColumn
        
        Private columnV_TAX_REG_NO As Global.System.Data.DataColumn
        
        Private columnGST As Global.System.Data.DataColumn
        
        Private columnAmount As Global.System.Data.DataColumn
        
        Private columnIM_INVOICE_NO As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DataTable1"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_COY_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_COY_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_ADDR_LINE1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_ADDR_LINE1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_ADDR_LINE2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_ADDR_LINE2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_ADDR_LINE3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_ADDR_LINE3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_POSTCODEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_POSTCODE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_CITYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_CITY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_STATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_STATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_COUNTRYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_COUNTRY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_BUSINESS_REG_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_BUSINESS_REG_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_EMAILColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_EMAIL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_PHONEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_PHONE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_CN_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_CN_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_CREATED_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_CREATED_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_CN_TYPEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_CN_TYPE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_COY_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_COY_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_ADDR_LINE1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_ADDR_LINE1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_ADDR_LINE2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_ADDR_LINE2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_ADDR_LINE3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_ADDR_LINE3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_POSTCODEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_POSTCODE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_CITYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_CITY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_STATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_STATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_COUNTRYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_COUNTRY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IM_SHIP_AMTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIM_SHIP_AMT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IM_WITHHOLDING_TAXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIM_WITHHOLDING_TAX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_REMARKSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_REMARKS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_EXCHANGE_RATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_EXCHANGE_RATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CND_CN_LINEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCND_CN_LINE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ID_PRODUCT_DESCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_PRODUCT_DESC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ID_UOMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_UOM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ID_GSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_GST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ID_GST_RATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_GST_RATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CND_QTYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCND_QTY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CND_UNIT_COSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCND_UNIT_COST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CND_REMARKSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCND_REMARKS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CNM_CURRENCY_CODEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCNM_CURRENCY_CODE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property V_TAX_REG_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnV_TAX_REG_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property AmountColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAmount
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IM_INVOICE_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIM_INVOICE_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DataTable1Row
            Get
                Return CType(Me.Rows(index),DataTable1Row)
            End Get
        End Property
        
        Public Event DataTable1RowChanging As DataTable1RowChangeEventHandler
        
        Public Event DataTable1RowChanged As DataTable1RowChangeEventHandler
        
        Public Event DataTable1RowDeleting As DataTable1RowChangeEventHandler
        
        Public Event DataTable1RowDeleted As DataTable1RowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddDataTable1Row(ByVal row As DataTable1Row)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddDataTable1Row( _
                    ByVal V_COY_NAME As String,  _
                    ByVal V_ADDR_LINE1 As String,  _
                    ByVal V_ADDR_LINE2 As String,  _
                    ByVal V_ADDR_LINE3 As String,  _
                    ByVal V_POSTCODE As String,  _
                    ByVal V_CITY As String,  _
                    ByVal V_STATE As String,  _
                    ByVal V_COUNTRY As String,  _
                    ByVal V_BUSINESS_REG_NO As String,  _
                    ByVal V_EMAIL As String,  _
                    ByVal V_PHONE As String,  _
                    ByVal CNM_CN_NO As String,  _
                    ByVal CNM_CREATED_DATE As Date,  _
                    ByVal CNM_CN_TYPE As String,  _
                    ByVal B_COY_NAME As String,  _
                    ByVal B_ADDR_LINE1 As String,  _
                    ByVal B_ADDR_LINE2 As String,  _
                    ByVal B_ADDR_LINE3 As String,  _
                    ByVal B_POSTCODE As String,  _
                    ByVal B_CITY As String,  _
                    ByVal B_STATE As String,  _
                    ByVal B_COUNTRY As String,  _
                    ByVal IM_SHIP_AMT As Decimal,  _
                    ByVal IM_WITHHOLDING_TAX As Integer,  _
                    ByVal CNM_REMARKS As String,  _
                    ByVal CNM_EXCHANGE_RATE As Double,  _
                    ByVal CND_CN_LINE As Integer,  _
                    ByVal ID_PRODUCT_DESC As String,  _
                    ByVal ID_UOM As String,  _
                    ByVal ID_GST As Decimal,  _
                    ByVal ID_GST_RATE As String,  _
                    ByVal CND_QTY As Decimal,  _
                    ByVal CND_UNIT_COST As Decimal,  _
                    ByVal CND_REMARKS As String,  _
                    ByVal CNM_CURRENCY_CODE As String,  _
                    ByVal V_TAX_REG_NO As String,  _
                    ByVal GST As String,  _
                    ByVal Amount As String,  _
                    ByVal IM_INVOICE_NO As String) As DataTable1Row
            Dim rowDataTable1Row As DataTable1Row = CType(Me.NewRow,DataTable1Row)
            Dim columnValuesArray() As Object = New Object() {V_COY_NAME, V_ADDR_LINE1, V_ADDR_LINE2, V_ADDR_LINE3, V_POSTCODE, V_CITY, V_STATE, V_COUNTRY, V_BUSINESS_REG_NO, V_EMAIL, V_PHONE, CNM_CN_NO, CNM_CREATED_DATE, CNM_CN_TYPE, B_COY_NAME, B_ADDR_LINE1, B_ADDR_LINE2, B_ADDR_LINE3, B_POSTCODE, B_CITY, B_STATE, B_COUNTRY, IM_SHIP_AMT, IM_WITHHOLDING_TAX, CNM_REMARKS, CNM_EXCHANGE_RATE, CND_CN_LINE, ID_PRODUCT_DESC, ID_UOM, ID_GST, ID_GST_RATE, CND_QTY, CND_UNIT_COST, CND_REMARKS, CNM_CURRENCY_CODE, V_TAX_REG_NO, GST, Amount, IM_INVOICE_NO}
            rowDataTable1Row.ItemArray = columnValuesArray
            Me.Rows.Add(rowDataTable1Row)
            Return rowDataTable1Row
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByCND_CN_LINE(ByVal CND_CN_LINE As Integer) As DataTable1Row
            Return CType(Me.Rows.Find(New Object() {CND_CN_LINE}),DataTable1Row)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DataTable1DataTable = CType(MyBase.Clone,DataTable1DataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DataTable1DataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnV_COY_NAME = MyBase.Columns("V_COY_NAME")
            Me.columnV_ADDR_LINE1 = MyBase.Columns("V_ADDR_LINE1")
            Me.columnV_ADDR_LINE2 = MyBase.Columns("V_ADDR_LINE2")
            Me.columnV_ADDR_LINE3 = MyBase.Columns("V_ADDR_LINE3")
            Me.columnV_POSTCODE = MyBase.Columns("V_POSTCODE")
            Me.columnV_CITY = MyBase.Columns("V_CITY")
            Me.columnV_STATE = MyBase.Columns("V_STATE")
            Me.columnV_COUNTRY = MyBase.Columns("V_COUNTRY")
            Me.columnV_BUSINESS_REG_NO = MyBase.Columns("V_BUSINESS_REG_NO")
            Me.columnV_EMAIL = MyBase.Columns("V_EMAIL")
            Me.columnV_PHONE = MyBase.Columns("V_PHONE")
            Me.columnCNM_CN_NO = MyBase.Columns("CNM_CN_NO")
            Me.columnCNM_CREATED_DATE = MyBase.Columns("CNM_CREATED_DATE")
            Me.columnCNM_CN_TYPE = MyBase.Columns("CNM_CN_TYPE")
            Me.columnB_COY_NAME = MyBase.Columns("B_COY_NAME")
            Me.columnB_ADDR_LINE1 = MyBase.Columns("B_ADDR_LINE1")
            Me.columnB_ADDR_LINE2 = MyBase.Columns("B_ADDR_LINE2")
            Me.columnB_ADDR_LINE3 = MyBase.Columns("B_ADDR_LINE3")
            Me.columnB_POSTCODE = MyBase.Columns("B_POSTCODE")
            Me.columnB_CITY = MyBase.Columns("B_CITY")
            Me.columnB_STATE = MyBase.Columns("B_STATE")
            Me.columnB_COUNTRY = MyBase.Columns("B_COUNTRY")
            Me.columnIM_SHIP_AMT = MyBase.Columns("IM_SHIP_AMT")
            Me.columnIM_WITHHOLDING_TAX = MyBase.Columns("IM_WITHHOLDING_TAX")
            Me.columnCNM_REMARKS = MyBase.Columns("CNM_REMARKS")
            Me.columnCNM_EXCHANGE_RATE = MyBase.Columns("CNM_EXCHANGE_RATE")
            Me.columnCND_CN_LINE = MyBase.Columns("CND_CN_LINE")
            Me.columnID_PRODUCT_DESC = MyBase.Columns("ID_PRODUCT_DESC")
            Me.columnID_UOM = MyBase.Columns("ID_UOM")
            Me.columnID_GST = MyBase.Columns("ID_GST")
            Me.columnID_GST_RATE = MyBase.Columns("ID_GST_RATE")
            Me.columnCND_QTY = MyBase.Columns("CND_QTY")
            Me.columnCND_UNIT_COST = MyBase.Columns("CND_UNIT_COST")
            Me.columnCND_REMARKS = MyBase.Columns("CND_REMARKS")
            Me.columnCNM_CURRENCY_CODE = MyBase.Columns("CNM_CURRENCY_CODE")
            Me.columnV_TAX_REG_NO = MyBase.Columns("V_TAX_REG_NO")
            Me.columnGST = MyBase.Columns("GST")
            Me.columnAmount = MyBase.Columns("Amount")
            Me.columnIM_INVOICE_NO = MyBase.Columns("IM_INVOICE_NO")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnV_COY_NAME = New Global.System.Data.DataColumn("V_COY_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_COY_NAME)
            Me.columnV_ADDR_LINE1 = New Global.System.Data.DataColumn("V_ADDR_LINE1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_ADDR_LINE1)
            Me.columnV_ADDR_LINE2 = New Global.System.Data.DataColumn("V_ADDR_LINE2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_ADDR_LINE2)
            Me.columnV_ADDR_LINE3 = New Global.System.Data.DataColumn("V_ADDR_LINE3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_ADDR_LINE3)
            Me.columnV_POSTCODE = New Global.System.Data.DataColumn("V_POSTCODE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_POSTCODE)
            Me.columnV_CITY = New Global.System.Data.DataColumn("V_CITY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_CITY)
            Me.columnV_STATE = New Global.System.Data.DataColumn("V_STATE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_STATE)
            Me.columnV_COUNTRY = New Global.System.Data.DataColumn("V_COUNTRY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_COUNTRY)
            Me.columnV_BUSINESS_REG_NO = New Global.System.Data.DataColumn("V_BUSINESS_REG_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_BUSINESS_REG_NO)
            Me.columnV_EMAIL = New Global.System.Data.DataColumn("V_EMAIL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_EMAIL)
            Me.columnV_PHONE = New Global.System.Data.DataColumn("V_PHONE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_PHONE)
            Me.columnCNM_CN_NO = New Global.System.Data.DataColumn("CNM_CN_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_CN_NO)
            Me.columnCNM_CREATED_DATE = New Global.System.Data.DataColumn("CNM_CREATED_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_CREATED_DATE)
            Me.columnCNM_CN_TYPE = New Global.System.Data.DataColumn("CNM_CN_TYPE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_CN_TYPE)
            Me.columnB_COY_NAME = New Global.System.Data.DataColumn("B_COY_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_COY_NAME)
            Me.columnB_ADDR_LINE1 = New Global.System.Data.DataColumn("B_ADDR_LINE1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_ADDR_LINE1)
            Me.columnB_ADDR_LINE2 = New Global.System.Data.DataColumn("B_ADDR_LINE2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_ADDR_LINE2)
            Me.columnB_ADDR_LINE3 = New Global.System.Data.DataColumn("B_ADDR_LINE3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_ADDR_LINE3)
            Me.columnB_POSTCODE = New Global.System.Data.DataColumn("B_POSTCODE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_POSTCODE)
            Me.columnB_CITY = New Global.System.Data.DataColumn("B_CITY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_CITY)
            Me.columnB_STATE = New Global.System.Data.DataColumn("B_STATE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_STATE)
            Me.columnB_COUNTRY = New Global.System.Data.DataColumn("B_COUNTRY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_COUNTRY)
            Me.columnIM_SHIP_AMT = New Global.System.Data.DataColumn("IM_SHIP_AMT", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIM_SHIP_AMT)
            Me.columnIM_WITHHOLDING_TAX = New Global.System.Data.DataColumn("IM_WITHHOLDING_TAX", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIM_WITHHOLDING_TAX)
            Me.columnCNM_REMARKS = New Global.System.Data.DataColumn("CNM_REMARKS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_REMARKS)
            Me.columnCNM_EXCHANGE_RATE = New Global.System.Data.DataColumn("CNM_EXCHANGE_RATE", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_EXCHANGE_RATE)
            Me.columnCND_CN_LINE = New Global.System.Data.DataColumn("CND_CN_LINE", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCND_CN_LINE)
            Me.columnID_PRODUCT_DESC = New Global.System.Data.DataColumn("ID_PRODUCT_DESC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_PRODUCT_DESC)
            Me.columnID_UOM = New Global.System.Data.DataColumn("ID_UOM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_UOM)
            Me.columnID_GST = New Global.System.Data.DataColumn("ID_GST", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_GST)
            Me.columnID_GST_RATE = New Global.System.Data.DataColumn("ID_GST_RATE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_GST_RATE)
            Me.columnCND_QTY = New Global.System.Data.DataColumn("CND_QTY", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCND_QTY)
            Me.columnCND_UNIT_COST = New Global.System.Data.DataColumn("CND_UNIT_COST", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCND_UNIT_COST)
            Me.columnCND_REMARKS = New Global.System.Data.DataColumn("CND_REMARKS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCND_REMARKS)
            Me.columnCNM_CURRENCY_CODE = New Global.System.Data.DataColumn("CNM_CURRENCY_CODE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCNM_CURRENCY_CODE)
            Me.columnV_TAX_REG_NO = New Global.System.Data.DataColumn("V_TAX_REG_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnV_TAX_REG_NO)
            Me.columnGST = New Global.System.Data.DataColumn("GST", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGST)
            Me.columnAmount = New Global.System.Data.DataColumn("Amount", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAmount)
            Me.columnIM_INVOICE_NO = New Global.System.Data.DataColumn("IM_INVOICE_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIM_INVOICE_NO)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnCND_CN_LINE}, true))
            Me.columnV_COY_NAME.AllowDBNull = false
            Me.columnV_COY_NAME.MaxLength = 100
            Me.columnV_ADDR_LINE1.MaxLength = 255
            Me.columnV_ADDR_LINE2.MaxLength = 255
            Me.columnV_ADDR_LINE3.MaxLength = 255
            Me.columnV_POSTCODE.MaxLength = 10
            Me.columnV_CITY.MaxLength = 50
            Me.columnV_STATE.MaxLength = 50
            Me.columnV_COUNTRY.MaxLength = 50
            Me.columnV_BUSINESS_REG_NO.MaxLength = 50
            Me.columnV_EMAIL.MaxLength = 50
            Me.columnV_PHONE.MaxLength = 50
            Me.columnCNM_CN_NO.AllowDBNull = false
            Me.columnCNM_CN_NO.MaxLength = 20
            Me.columnCNM_CN_TYPE.AllowDBNull = false
            Me.columnCNM_CN_TYPE.MaxLength = 10
            Me.columnB_COY_NAME.AllowDBNull = false
            Me.columnB_COY_NAME.MaxLength = 100
            Me.columnB_ADDR_LINE1.AllowDBNull = false
            Me.columnB_ADDR_LINE1.MaxLength = 255
            Me.columnB_ADDR_LINE2.AllowDBNull = false
            Me.columnB_ADDR_LINE2.MaxLength = 255
            Me.columnB_ADDR_LINE3.AllowDBNull = false
            Me.columnB_ADDR_LINE3.MaxLength = 255
            Me.columnB_POSTCODE.AllowDBNull = false
            Me.columnB_POSTCODE.MaxLength = 10
            Me.columnB_CITY.AllowDBNull = false
            Me.columnB_CITY.MaxLength = 50
            Me.columnB_STATE.MaxLength = 50
            Me.columnB_COUNTRY.MaxLength = 50
            Me.columnCNM_REMARKS.MaxLength = 1000
            Me.columnCND_CN_LINE.AllowDBNull = false
            Me.columnCND_CN_LINE.Unique = true
            Me.columnID_PRODUCT_DESC.MaxLength = 500
            Me.columnID_UOM.MaxLength = 20
            Me.columnID_GST_RATE.MaxLength = 10
            Me.columnCND_REMARKS.MaxLength = 1000
            Me.columnCNM_CURRENCY_CODE.AllowDBNull = false
            Me.columnCNM_CURRENCY_CODE.MaxLength = 10
            Me.columnV_TAX_REG_NO.MaxLength = 50
            Me.columnGST.AllowDBNull = false
            Me.columnAmount.AllowDBNull = false
            Me.columnIM_INVOICE_NO.MaxLength = 50
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewDataTable1Row() As DataTable1Row
            Return CType(Me.NewRow,DataTable1Row)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DataTable1Row(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DataTable1Row)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DataTable1RowChangedEvent) Is Nothing) Then
                RaiseEvent DataTable1RowChanged(Me, New DataTable1RowChangeEvent(CType(e.Row,DataTable1Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DataTable1RowChangingEvent) Is Nothing) Then
                RaiseEvent DataTable1RowChanging(Me, New DataTable1RowChangeEvent(CType(e.Row,DataTable1Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DataTable1RowDeletedEvent) Is Nothing) Then
                RaiseEvent DataTable1RowDeleted(Me, New DataTable1RowChangeEvent(CType(e.Row,DataTable1Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DataTable1RowDeletingEvent) Is Nothing) Then
                RaiseEvent DataTable1RowDeleting(Me, New DataTable1RowChangeEvent(CType(e.Row,DataTable1Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveDataTable1Row(ByVal row As DataTable1Row)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As PreviewCN = New PreviewCN
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DataTable1DataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class DataTable1Row
        Inherits Global.System.Data.DataRow
        
        Private tableDataTable1 As DataTable1DataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDataTable1 = CType(Me.Table,DataTable1DataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_COY_NAME() As String
            Get
                Return CType(Me(Me.tableDataTable1.V_COY_NAMEColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.V_COY_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_ADDR_LINE1() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_ADDR_LINE1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_ADDR_LINE1' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_ADDR_LINE1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_ADDR_LINE2() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_ADDR_LINE2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_ADDR_LINE2' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_ADDR_LINE2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_ADDR_LINE3() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_ADDR_LINE3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_ADDR_LINE3' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_ADDR_LINE3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_POSTCODE() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_POSTCODEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_POSTCODE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_POSTCODEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_CITY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_CITYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_CITY' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_CITYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_STATE() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_STATEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_STATE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_STATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_COUNTRY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_COUNTRYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_COUNTRY' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_COUNTRYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_BUSINESS_REG_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_BUSINESS_REG_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_BUSINESS_REG_NO' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_BUSINESS_REG_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_EMAIL() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_EMAILColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_EMAIL' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_EMAILColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_PHONE() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_PHONEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_PHONE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_PHONEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_CN_NO() As String
            Get
                Return CType(Me(Me.tableDataTable1.CNM_CN_NOColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.CNM_CN_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_CREATED_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CNM_CREATED_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CNM_CREATED_DATE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CNM_CREATED_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_CN_TYPE() As String
            Get
                Return CType(Me(Me.tableDataTable1.CNM_CN_TYPEColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.CNM_CN_TYPEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_COY_NAME() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_COY_NAMEColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_COY_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_ADDR_LINE1() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_ADDR_LINE1Column),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_ADDR_LINE1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_ADDR_LINE2() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_ADDR_LINE2Column),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_ADDR_LINE2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_ADDR_LINE3() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_ADDR_LINE3Column),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_ADDR_LINE3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_POSTCODE() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_POSTCODEColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_POSTCODEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_CITY() As String
            Get
                Return CType(Me(Me.tableDataTable1.B_CITYColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.B_CITYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_STATE() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.B_STATEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_STATE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.B_STATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_COUNTRY() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.B_COUNTRYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_COUNTRY' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.B_COUNTRYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IM_SHIP_AMT() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.IM_SHIP_AMTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IM_SHIP_AMT' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.IM_SHIP_AMTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IM_WITHHOLDING_TAX() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.IM_WITHHOLDING_TAXColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IM_WITHHOLDING_TAX' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.IM_WITHHOLDING_TAXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_REMARKS() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CNM_REMARKSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CNM_REMARKS' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CNM_REMARKSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_EXCHANGE_RATE() As Double
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CNM_EXCHANGE_RATEColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CNM_EXCHANGE_RATE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CNM_EXCHANGE_RATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CND_CN_LINE() As Integer
            Get
                Return CType(Me(Me.tableDataTable1.CND_CN_LINEColumn),Integer)
            End Get
            Set
                Me(Me.tableDataTable1.CND_CN_LINEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID_PRODUCT_DESC() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.ID_PRODUCT_DESCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_PRODUCT_DESC' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.ID_PRODUCT_DESCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID_UOM() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.ID_UOMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_UOM' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.ID_UOMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID_GST() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.ID_GSTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_GST' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.ID_GSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID_GST_RATE() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.ID_GST_RATEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_GST_RATE' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.ID_GST_RATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CND_QTY() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CND_QTYColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CND_QTY' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CND_QTYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CND_UNIT_COST() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CND_UNIT_COSTColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CND_UNIT_COST' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CND_UNIT_COSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CND_REMARKS() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.CND_REMARKSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CND_REMARKS' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.CND_REMARKSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CNM_CURRENCY_CODE() As String
            Get
                Return CType(Me(Me.tableDataTable1.CNM_CURRENCY_CODEColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.CNM_CURRENCY_CODEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property V_TAX_REG_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.V_TAX_REG_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'V_TAX_REG_NO' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.V_TAX_REG_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GST() As String
            Get
                Return CType(Me(Me.tableDataTable1.GSTColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.GSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Amount() As String
            Get
                Return CType(Me(Me.tableDataTable1.AmountColumn),String)
            End Get
            Set
                Me(Me.tableDataTable1.AmountColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property IM_INVOICE_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tableDataTable1.IM_INVOICE_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'IM_INVOICE_NO' in table 'DataTable1' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDataTable1.IM_INVOICE_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_ADDR_LINE1Null() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_ADDR_LINE1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_ADDR_LINE1Null()
            Me(Me.tableDataTable1.V_ADDR_LINE1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_ADDR_LINE2Null() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_ADDR_LINE2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_ADDR_LINE2Null()
            Me(Me.tableDataTable1.V_ADDR_LINE2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_ADDR_LINE3Null() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_ADDR_LINE3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_ADDR_LINE3Null()
            Me(Me.tableDataTable1.V_ADDR_LINE3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_POSTCODENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_POSTCODEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_POSTCODENull()
            Me(Me.tableDataTable1.V_POSTCODEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_CITYNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_CITYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_CITYNull()
            Me(Me.tableDataTable1.V_CITYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_STATENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_STATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_STATENull()
            Me(Me.tableDataTable1.V_STATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_COUNTRYNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_COUNTRYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_COUNTRYNull()
            Me(Me.tableDataTable1.V_COUNTRYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_BUSINESS_REG_NONull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_BUSINESS_REG_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_BUSINESS_REG_NONull()
            Me(Me.tableDataTable1.V_BUSINESS_REG_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_EMAILNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_EMAILColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_EMAILNull()
            Me(Me.tableDataTable1.V_EMAILColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_PHONENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_PHONEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_PHONENull()
            Me(Me.tableDataTable1.V_PHONEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCNM_CREATED_DATENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CNM_CREATED_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCNM_CREATED_DATENull()
            Me(Me.tableDataTable1.CNM_CREATED_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_STATENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.B_STATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_STATENull()
            Me(Me.tableDataTable1.B_STATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_COUNTRYNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.B_COUNTRYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_COUNTRYNull()
            Me(Me.tableDataTable1.B_COUNTRYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIM_SHIP_AMTNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.IM_SHIP_AMTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIM_SHIP_AMTNull()
            Me(Me.tableDataTable1.IM_SHIP_AMTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIM_WITHHOLDING_TAXNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.IM_WITHHOLDING_TAXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIM_WITHHOLDING_TAXNull()
            Me(Me.tableDataTable1.IM_WITHHOLDING_TAXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCNM_REMARKSNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CNM_REMARKSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCNM_REMARKSNull()
            Me(Me.tableDataTable1.CNM_REMARKSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCNM_EXCHANGE_RATENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CNM_EXCHANGE_RATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCNM_EXCHANGE_RATENull()
            Me(Me.tableDataTable1.CNM_EXCHANGE_RATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsID_PRODUCT_DESCNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.ID_PRODUCT_DESCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetID_PRODUCT_DESCNull()
            Me(Me.tableDataTable1.ID_PRODUCT_DESCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsID_UOMNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.ID_UOMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetID_UOMNull()
            Me(Me.tableDataTable1.ID_UOMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsID_GSTNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.ID_GSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetID_GSTNull()
            Me(Me.tableDataTable1.ID_GSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsID_GST_RATENull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.ID_GST_RATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetID_GST_RATENull()
            Me(Me.tableDataTable1.ID_GST_RATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCND_QTYNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CND_QTYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCND_QTYNull()
            Me(Me.tableDataTable1.CND_QTYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCND_UNIT_COSTNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CND_UNIT_COSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCND_UNIT_COSTNull()
            Me(Me.tableDataTable1.CND_UNIT_COSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCND_REMARKSNull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.CND_REMARKSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCND_REMARKSNull()
            Me(Me.tableDataTable1.CND_REMARKSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsV_TAX_REG_NONull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.V_TAX_REG_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetV_TAX_REG_NONull()
            Me(Me.tableDataTable1.V_TAX_REG_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsIM_INVOICE_NONull() As Boolean
            Return Me.IsNull(Me.tableDataTable1.IM_INVOICE_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetIM_INVOICE_NONull()
            Me(Me.tableDataTable1.IM_INVOICE_NOColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class DataTable1RowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DataTable1Row
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As DataTable1Row, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As DataTable1Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace PreviewCNTableAdapters
    
    '''<summary>
    '''Represents the connection and commands used to retrieve and save data.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
     Global.System.ComponentModel.ToolboxItem(true),  _
     Global.System.ComponentModel.DataObjectAttribute(true),  _
     Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class DataTable1TableAdapter
        Inherits Global.System.ComponentModel.Component
        
        Private WithEvents _adapter As Global.MySql.Data.MySqlClient.MySqlDataAdapter
        
        Private _connection As Global.MySql.Data.MySqlClient.MySqlConnection
        
        Private _commandCollection() As Global.MySql.Data.MySqlClient.MySqlCommand
        
        Private _clearBeforeFill As Boolean
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private ReadOnly Property Adapter() As Global.MySql.Data.MySqlClient.MySqlDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Property Connection() As Global.MySql.Data.MySqlClient.MySqlConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),Global.MySql.Data.MySqlClient.MySqlCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected ReadOnly Property CommandCollection() As Global.MySql.Data.MySqlClient.MySqlCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitAdapter()
            Me._adapter = New Global.MySql.Data.MySqlClient.MySqlDataAdapter
            Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "DataTable1"
            tableMapping.ColumnMappings.Add("V_COY_NAME", "V_COY_NAME")
            tableMapping.ColumnMappings.Add("V_ADDR_LINE1", "V_ADDR_LINE1")
            tableMapping.ColumnMappings.Add("V_ADDR_LINE2", "V_ADDR_LINE2")
            tableMapping.ColumnMappings.Add("V_ADDR_LINE3", "V_ADDR_LINE3")
            tableMapping.ColumnMappings.Add("V_POSTCODE", "V_POSTCODE")
            tableMapping.ColumnMappings.Add("V_CITY", "V_CITY")
            tableMapping.ColumnMappings.Add("V_STATE", "V_STATE")
            tableMapping.ColumnMappings.Add("V_COUNTRY", "V_COUNTRY")
            tableMapping.ColumnMappings.Add("V_BUSINESS_REG_NO", "V_BUSINESS_REG_NO")
            tableMapping.ColumnMappings.Add("V_EMAIL", "V_EMAIL")
            tableMapping.ColumnMappings.Add("V_PHONE", "V_PHONE")
            tableMapping.ColumnMappings.Add("CNM_CN_NO", "CNM_CN_NO")
            tableMapping.ColumnMappings.Add("CNM_CREATED_DATE", "CNM_CREATED_DATE")
            tableMapping.ColumnMappings.Add("CNM_CN_TYPE", "CNM_CN_TYPE")
            tableMapping.ColumnMappings.Add("B_COY_NAME", "B_COY_NAME")
            tableMapping.ColumnMappings.Add("B_ADDR_LINE1", "B_ADDR_LINE1")
            tableMapping.ColumnMappings.Add("B_ADDR_LINE2", "B_ADDR_LINE2")
            tableMapping.ColumnMappings.Add("B_ADDR_LINE3", "B_ADDR_LINE3")
            tableMapping.ColumnMappings.Add("B_POSTCODE", "B_POSTCODE")
            tableMapping.ColumnMappings.Add("B_CITY", "B_CITY")
            tableMapping.ColumnMappings.Add("B_STATE", "B_STATE")
            tableMapping.ColumnMappings.Add("B_COUNTRY", "B_COUNTRY")
            tableMapping.ColumnMappings.Add("IM_SHIP_AMT", "IM_SHIP_AMT")
            tableMapping.ColumnMappings.Add("IM_WITHHOLDING_TAX", "IM_WITHHOLDING_TAX")
            tableMapping.ColumnMappings.Add("CNM_REMARKS", "CNM_REMARKS")
            tableMapping.ColumnMappings.Add("CNM_EXCHANGE_RATE", "CNM_EXCHANGE_RATE")
            tableMapping.ColumnMappings.Add("CND_CN_LINE", "CND_CN_LINE")
            tableMapping.ColumnMappings.Add("ID_PRODUCT_DESC", "ID_PRODUCT_DESC")
            tableMapping.ColumnMappings.Add("ID_UOM", "ID_UOM")
            tableMapping.ColumnMappings.Add("ID_GST", "ID_GST")
            tableMapping.ColumnMappings.Add("ID_GST_RATE", "ID_GST_RATE")
            tableMapping.ColumnMappings.Add("CND_QTY", "CND_QTY")
            tableMapping.ColumnMappings.Add("CND_UNIT_COST", "CND_UNIT_COST")
            tableMapping.ColumnMappings.Add("CND_REMARKS", "CND_REMARKS")
            tableMapping.ColumnMappings.Add("CNM_CURRENCY_CODE", "CNM_CURRENCY_CODE")
            tableMapping.ColumnMappings.Add("V_TAX_REG_NO", "V_TAX_REG_NO")
            tableMapping.ColumnMappings.Add("GST", "GST")
            tableMapping.ColumnMappings.Add("Amount", "Amount")
            tableMapping.ColumnMappings.Add("IM_INVOICE_NO", "IM_INVOICE_NO")
            Me._adapter.TableMappings.Add(tableMapping)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitConnection()
            Me._connection = New Global.MySql.Data.MySqlClient.MySqlConnection
            Me._connection.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings("eprocureConnectionString3").ConnectionString
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New Global.MySql.Data.MySqlClient.MySqlCommand(0) {}
            Me._commandCollection(0) = New Global.MySql.Data.MySqlClient.MySqlCommand
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT CM_S.CM_COY_NAME AS V_COY_NAME, CM_S.CM_ADDR_LINE1 AS V_ADDR_LINE1, CM_S.C"& _ 
                "M_ADDR_LINE2 AS V_ADDR_LINE2, CM_S.CM_ADDR_LINE3 AS V_ADDR_LINE3, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"CM_S.CM_POST"& _ 
                "CODE AS V_POSTCODE, CM_S.CM_CITY AS V_CITY, CM_S_STATE.CODE_DESC AS V_STATE, CM_"& _ 
                "S_COUNTRY.CODE_DESC AS V_COUNTRY, CM_S.CM_TAX_REG_NO AS V_TAX_REG_NO, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"CM_S.CM_"& _ 
                "BUSINESS_REG_NO AS V_BUSINESS_REG_NO, CM_S.CM_EMAIL AS V_EMAIL, CM_S.CM_PHONE AS"& _ 
                " V_PHONE, CNM_CN_NO, CNM_CREATED_DATE, CNM_CN_TYPE, CNM_CURRENCY_CODE, CM_B.CM_C"& _ 
                "OY_NAME AS B_COY_NAME, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"CNM_ADDR_LINE1 AS B_ADDR_LINE1, CNM_ADDR_LINE2 AS B_ADD"& _ 
                "R_LINE2, CNM_ADDR_LINE3 AS B_ADDR_LINE3, CNM_POSTCODE AS B_POSTCODE, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"CNM_CITY "& _ 
                "AS B_CITY, CM_B_STATE.CODE_DESC AS B_STATE, CM_B_COUNTRY.CODE_DESC AS B_COUNTRY,"& _ 
                " IM_SHIP_AMT, IM_WITHHOLDING_TAX, IM_INVOICE_NO,"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"CNM_REMARKS, CNM_EXCHANGE_RATE"& _ 
                ", CND_CN_LINE, ID_PRODUCT_DESC, ID_UOM, ID_GST, ID_GST_RATE, CND_QTY, CND_UNIT_C"& _ 
                "OST, CND_REMARKS, '' AS GST, '' AS Amount "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM CREDIT_NOTE_MSTR "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN C"& _ 
                "REDIT_NOTE_DETAILS ON CNM_CN_NO = CND_CN_NO AND CNM_CN_S_COY_ID = CND_CN_S_COY_I"& _ 
                "D "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN INVOICE_MSTR ON CNM_INV_NO = IM_INVOICE_NO AND CNM_CN_S_COY_ID = "& _ 
                "IM_S_COY_ID "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN INVOICE_DETAILS ON IM_INVOICE_NO = ID_INVOICE_NO AND IM"& _ 
                "_S_COY_ID = ID_S_COY_ID AND CND_INV_LINE = ID_INVOICE_LINE "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN COMPANY_"& _ 
                "MSTR CM_S ON CNM_CN_S_COY_ID = CM_S.CM_COY_ID "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN COMPANY_MSTR CM_B ON "& _ 
                "CNM_CN_B_COY_ID = CM_B.CM_COY_ID "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN CODE_MSTR CM_S_STATE ON CM_S.CM_ST"& _ 
                "ATE = CM_S_STATE.CODE_ABBR AND CM_S_STATE.CODE_CATEGORY = 'S' "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN CODE_"& _ 
                "MSTR CM_S_COUNTRY ON CM_S.CM_COUNTRY = CM_S_COUNTRY.CODE_ABBR AND CM_S_COUNTRY.C"& _ 
                "ODE_CATEGORY = 'CT' "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN CODE_MSTR CM_B_STATE ON CNM_STATE = CM_B_STATE."& _ 
                "CODE_ABBR AND CM_S_STATE.CODE_CATEGORY = 'S' "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"INNER JOIN CODE_MSTR CM_B_COUNTRY"& _ 
                " ON CNM_COUNTRY = CM_B_COUNTRY.CODE_ABBR AND CM_S_COUNTRY.CODE_CATEGORY = 'CT' "
            Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As PreviewCN.DataTable1DataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As PreviewCN.DataTable1DataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As PreviewCN.DataTable1DataTable = New PreviewCN.DataTable1DataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
    End Class
End Namespace
