'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class ReportFormatN9
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblHeader As System.Web.UI.WebControls.Label
    Protected WithEvents lblAction As System.Web.UI.WebControls.Label
    Protected WithEvents label2 As System.Web.UI.WebControls.Label
    Protected WithEvents lblCriteria As System.Web.UI.WebControls.Label
    Protected WithEvents Label4 As System.Web.UI.WebControls.Label
    Protected WithEvents txtDate As System.Web.UI.WebControls.TextBox
    Protected WithEvents trStatus As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label6 As System.Web.UI.WebControls.Label
    Protected WithEvents CheckBox1 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents CheckBox2 As System.Web.UI.WebControls.CheckBox
    Protected WithEvents Label20 As System.Web.UI.WebControls.Label
    Protected WithEvents hidFromGLCode As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label22 As System.Web.UI.WebControls.Label
    Protected WithEvents hidToGLCode As System.Web.UI.WebControls.TextBox
    Protected WithEvents trCode As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label14 As System.Web.UI.WebControls.Label
    Protected WithEvents txtBranchCode As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label16 As System.Web.UI.WebControls.Label
    Protected WithEvents txtCentreCode As System.Web.UI.WebControls.TextBox
    Protected WithEvents trDate As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label8 As System.Web.UI.WebControls.Label
    Protected WithEvents Label15 As System.Web.UI.WebControls.Label
    Protected WithEvents txtSDate As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label11 As System.Web.UI.WebControls.Label
    Protected WithEvents Label17 As System.Web.UI.WebControls.Label
    Protected WithEvents txtEDate As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label
    Protected WithEvents trPANo As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label9 As System.Web.UI.WebControls.Label
    Protected WithEvents txtBoxPA As System.Web.UI.WebControls.TextBox
    Protected WithEvents trTaxInvoice As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label19 As System.Web.UI.WebControls.Label
    Protected WithEvents txtTaxInvoice As System.Web.UI.WebControls.TextBox
    Protected WithEvents trBCNo As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label13 As System.Web.UI.WebControls.Label
    Protected WithEvents txtBoxBC As System.Web.UI.WebControls.TextBox
    Protected WithEvents trDebitNoteNo As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label12 As System.Web.UI.WebControls.Label
    Protected WithEvents txtDebitNoteNo As System.Web.UI.WebControls.TextBox
    Protected WithEvents Label18 As System.Web.UI.WebControls.Label
    Protected WithEvents Label29 As System.Web.UI.WebControls.Label
    Protected WithEvents Label0 As System.Web.UI.WebControls.Label
    Protected WithEvents Label21 As System.Web.UI.WebControls.Label
    Protected WithEvents Label23 As System.Web.UI.WebControls.Label
    Protected WithEvents Label24 As System.Web.UI.WebControls.Label
    Protected WithEvents trDebitAdviceNo As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label28 As System.Web.UI.WebControls.Label
    Protected WithEvents txtDebitAdviceNo As System.Web.UI.WebControls.TextBox
    Protected WithEvents trReportType As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label
    Protected WithEvents cboReportType As System.Web.UI.WebControls.DropDownList
    Protected WithEvents ValReportType As System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents Label7 As System.Web.UI.WebControls.Label
    Protected WithEvents cmdSubmit As System.Web.UI.WebControls.Button
    Protected WithEvents cmdClear As System.Web.UI.HtmlControls.HtmlInputButton
    Protected WithEvents vldSumm As System.Web.UI.WebControls.ValidationSummary
    Protected WithEvents lnkBack As System.Web.UI.WebControls.HyperLink
End Class
