'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class quoteTerm
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lbl_QuoteVal As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_ContactPer As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_ContNum As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_Email As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_pay_term As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_paymeth As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_ship_term As System.Web.UI.WebControls.Label
    Protected WithEvents lbl_shipmode As System.Web.UI.WebControls.Label
    Protected WithEvents txt_remark As System.Web.UI.WebControls.TextBox
    Protected WithEvents pnlAttach2 As System.Web.UI.WebControls.Panel
End Class
