'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class RFQ_List
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lbl_title As System.Web.UI.WebControls.Label
    Protected WithEvents hidAddItem As System.Web.UI.HtmlControls.HtmlInputHidden
    Protected WithEvents lbl_display As System.Web.UI.WebControls.Label
    Protected WithEvents txt_DocNum As System.Web.UI.WebControls.TextBox
    Protected WithEvents txt_VenName As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmd_Search As System.Web.UI.WebControls.Button
    Protected WithEvents cmd_clear As System.Web.UI.WebControls.Button
    Protected WithEvents ddl_folder As System.Web.UI.WebControls.DropDownList
    Protected WithEvents cmd_NewRFQ As System.Web.UI.WebControls.Button
    Protected WithEvents img_delete As System.Web.UI.WebControls.ImageButton
    Protected WithEvents img_pdf As System.Web.UI.WebControls.ImageButton
    Protected WithEvents ImageButton2 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents ImageButton5 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents dtg_VendorList As System.Web.UI.WebControls.DataGrid
    Protected WithEvents dtg_Draft As System.Web.UI.WebControls.DataGrid
    Protected WithEvents dtg_Qoute As System.Web.UI.WebControls.DataGrid
    Protected WithEvents dtg_Trash As System.Web.UI.WebControls.DataGrid
    Protected WithEvents cmd_emp_trash As System.Web.UI.WebControls.Button
    Protected WithEvents Imagebutton1 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents img_pdf2 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents ImageButton3 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents ImageButton6 As System.Web.UI.WebControls.ImageButton
    Protected WithEvents lblCurrentIndex As System.Web.UI.WebControls.Label
End Class
