'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class CatalogueConfirm
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblTitle As System.Web.UI.WebControls.Label
    Protected WithEvents trCode As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblCode As System.Web.UI.WebControls.Label
    Protected WithEvents trHeader As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblPR As System.Web.UI.WebControls.Label
    Protected WithEvents trDetails As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblDetail As System.Web.UI.WebControls.Label
    Protected WithEvents trHeaderBlank As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents trNotHeader As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblNotHeader As System.Web.UI.WebControls.Label
    Protected WithEvents trNotDetail As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblNotDetail As System.Web.UI.WebControls.Label
    Protected WithEvents trRemark As System.Web.UI.HtmlControls.HtmlTableRow
    Protected WithEvents lblRemark As System.Web.UI.WebControls.Label
    Protected WithEvents lnkBack As System.Web.UI.WebControls.HyperLink
End Class
